### PR TITLE
Proposed Travis config

### PR DESCRIPTION
**Pull request by kjetilk**
Perhaps this Travis config would work?

### CODE REVIEW

**Comment by tobyink** [comment]
I always use my own very ancient fork of travis-perl. I should give the newer version a try.

**Comment by kjetilk** [comment]
> I always use my own very ancient fork of travis-perl. I should give the newer version a try.

Yup, works great with Dist::Inkt for me!

**Comment by tobyink** [comment]
Done, and I'm starting to move my distributions away from my old fork of travis-perl.

**Comment by kjetilk** [comment]
Great stuff! BTW, if you're moving towards git these days, I have made https://metacpan.org/pod/Dist::Inkt::Role::Git

**Comment by tobyink** [comment]
Git confuses me. I use Mercurial with the hg-git plugin to push/pull to/from Github.

**Comment by kjetilk** [comment]
> Git confuses me. I use Mercurial with the hg-git plugin to push/pull to/from Github.

Yeah. Sometimes it feels like going with a gun pointing at my foot. And yet, that's what I do... :-) 

BTW, have a look at Dist::Inkt::Role::AddExternalRDF, which I put in Dist::Inkt::DOAP. Makes it easier to augment the RDF with useful data. :-)

**Comment by tobyink** [comment]
The filtered data idea and the default `@base` are pretty clever.

**Pull request merged**
